using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Xunit;
namespace IntegrationTests;
public sealed class ApiTests(ApiFactory factory):IClassFixture<ApiFactory>{
  private static int nextClientIp=10;
  private static readonly object ValidConfig=new{schemaVersion=2,rooms=Array.Empty<object>(),openings=Array.Empty<object>(),furniture=Array.Empty<object>(),acUnits=Array.Empty<object>(),environment=new{outsideTempC=34,targetTempC=24}};
  private HttpClient Client(){var client=factory.CreateClient(new(){BaseAddress=new Uri("https://localhost"),HandleCookies=true});client.DefaultRequestHeaders.Add("X-Forwarded-For",$"203.0.113.{Interlocked.Increment(ref nextClientIp)%240+10}");return client;}
  private static async Task Authenticate(HttpClient client,string email){var password="Valid!Password123";var register=await client.PostAsJsonAsync("/api/auth/register",new{email,password});Assert.True(register.IsSuccessStatusCode,await register.Content.ReadAsStringAsync());var login=await client.PostAsJsonAsync("/api/auth/login?useCookies=true",new{email,password});Assert.True(login.IsSuccessStatusCode,await login.Content.ReadAsStringAsync());}
  [Fact]public async Task Health_is_public_but_projects_require_auth(){var client=Client();Assert.Equal(HttpStatusCode.OK,(await client.GetAsync("/health/live")).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await client.GetAsync("/api/projects")).StatusCode);}
  [Fact]public async Task Owner_crud_concurrency_and_idor_are_enforced(){var owner=Client();await Authenticate(owner,$"owner-{Guid.NewGuid():N}@test.local");Assert.Equal(HttpStatusCode.BadRequest,(await owner.PostAsJsonAsync("/api/projects",new{name="  ",configJson=JsonSerializer.Serialize(ValidConfig)})).StatusCode);var create=await owner.PostAsJsonAsync("/api/projects",new{name="Golden two rooms",configJson=JsonSerializer.Serialize(ValidConfig)});Assert.Equal(HttpStatusCode.Created,create.StatusCode);var project=await create.Content.ReadFromJsonAsync<JsonElement>();var id=project.GetProperty("id").GetGuid();var revision=project.GetProperty("revision").GetInt64();var conflict=await owner.PutAsJsonAsync($"/api/projects/{id}/draft",new{configJson=JsonSerializer.Serialize(ValidConfig),expectedRevision=revision-1,reason="stale"});Assert.Equal(HttpStatusCode.Conflict,conflict.StatusCode);Assert.Equal(HttpStatusCode.OK,(await owner.GetAsync($"/api/projects/{id}/versions")).StatusCode);var stranger=Client();await Authenticate(stranger,$"other-{Guid.NewGuid():N}@test.local");Assert.Equal(HttpStatusCode.NotFound,(await stranger.GetAsync($"/api/projects/{id}")).StatusCode);Assert.Equal(HttpStatusCode.NotFound,(await stranger.GetAsync($"/api/projects/{id}/versions")).StatusCode);Assert.Equal(HttpStatusCode.NotFound,(await stranger.GetAsync($"/api/projects/{id}/reports")).StatusCode);Assert.Equal(HttpStatusCode.NoContent,(await owner.DeleteAsync($"/api/projects/{id}")).StatusCode);Assert.Equal(HttpStatusCode.NotFound,(await owner.GetAsync($"/api/projects/{id}")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await owner.PostAsJsonAsync($"/api/projects/{id}/restore",new{})).StatusCode);}
  [Fact]public async Task Share_token_is_read_only_expirable_and_revocable(){var client=Client();await Authenticate(client,$"share-{Guid.NewGuid():N}@test.local");var create=await client.PostAsJsonAsync("/api/projects",new{name="Share",configJson=JsonSerializer.Serialize(ValidConfig)});var project=await create.Content.ReadFromJsonAsync<JsonElement>();var id=project.GetProperty("id").GetGuid();var share=await client.PostAsJsonAsync($"/api/projects/{id}/shares",new{expiresAt=DateTime.UtcNow.AddHours(1)});Assert.Equal(HttpStatusCode.Created,share.StatusCode);var link=await share.Content.ReadFromJsonAsync<JsonElement>();var token=link.GetProperty("token").GetString();var shareId=link.GetProperty("id").GetGuid();Assert.Equal(HttpStatusCode.OK,(await Client().GetAsync($"/api/shared/{token}")).StatusCode);Assert.Equal(HttpStatusCode.NoContent,(await client.DeleteAsync($"/api/projects/{id}/shares/{shareId}")).StatusCode);Assert.Equal(HttpStatusCode.NotFound,(await Client().GetAsync($"/api/shared/{token}")).StatusCode);}
  [Fact]public async Task Account_export_and_delete_are_owner_scoped(){var client=Client();await Authenticate(client,$"erase-{Guid.NewGuid():N}@test.local");await client.PostAsJsonAsync("/api/projects",new{name="Private",configJson=JsonSerializer.Serialize(ValidConfig)});var export=await client.GetAsync("/api/account/export");Assert.Equal(HttpStatusCode.OK,export.StatusCode);Assert.Contains("Private",await export.Content.ReadAsStringAsync());Assert.Equal(HttpStatusCode.NoContent,(await client.DeleteAsync("/api/account")).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await client.GetAsync("/api/projects")).StatusCode);}
}
