using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using AcSimulator.Api.Application;
using AcSimulator.Api.Domain;
using AcSimulator.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;

namespace AcSimulator.Api.Modules;
public static class Endpoints {
  private static string? UserId(ClaimsPrincipal user)=>user.FindFirstValue(ClaimTypes.NameIdentifier);
  private static ProjectDto Dto(Project p)=>new(p.Id,p.Name,p.Revision,p.CurrentVersionId,p.ConfigJson,p.ThumbnailUrl,p.CreatedAt,p.UpdatedAt);
  private static ScenarioDto Dto(Scenario s)=>new(s.Id,s.Name,s.BaseVersionId,s.SimulationConfigJson,s.ResultSummaryJson,s.CreatedAt);
  private static ReportDto Dto(Report r)=>new(r.Id,r.ScenarioId,r.Status,r.FileUrl,r.Error,r.CreatedAt,r.CompletedAt);
  private static IResult InvalidConfig(string error)=>Results.Problem(statusCode:422,title:"Invalid project configuration",detail:error);
  private static bool ValidName(string? name)=>!string.IsNullOrWhiteSpace(name)&&name.Trim().Length<=120;
  private static IResult Conflict(long revision)=>Results.Problem(statusCode:409,title:"Revision conflict",detail:"The server project changed since this draft was loaded.",extensions:new Dictionary<string,object?>{{"serverRevision",revision}});
  private static async Task<Project?> Owned(AppDbContext db,ClaimsPrincipal user,Guid id,bool includeDeleted=false,CancellationToken ct=default){var uid=UserId(user);if(uid is null)return null;var query=includeDeleted?db.Projects.IgnoreQueryFilters():db.Projects;return await query.SingleOrDefaultAsync(x=>x.Id==id&&x.OwnerId==uid,ct);}

  public static void MapProjectEndpoints(this WebApplication app){var group=app.MapGroup("/api/projects").RequireAuthorization().RequireRateLimiting("standard");
    group.MapGet("/",async(AppDbContext db,ClaimsPrincipal user,string? search="",string sort="updated",int page=1,int pageSize=20,CancellationToken ct=default)=>{var uid=UserId(user)!;page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,1,50);var q=db.Projects.AsNoTracking().Where(x=>x.OwnerId==uid);if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.Name.Contains(search));q=sort=="name"?q.OrderBy(x=>x.Name):q.OrderByDescending(x=>x.UpdatedAt);var total=await q.CountAsync(ct);var items=await q.Skip((page-1)*pageSize).Take(pageSize).Select(x=>Dto(x)).ToListAsync(ct);return Results.Ok(new PagedResponse<ProjectDto>(items,page,pageSize,total));});
    group.MapGet("/archived",async(AppDbContext db,ClaimsPrincipal user,CancellationToken ct)=>{var uid=UserId(user)!;var cutoff=DateTime.UtcNow.AddDays(-30);var items=await db.Projects.IgnoreQueryFilters().AsNoTracking().Where(x=>x.OwnerId==uid&&x.DeletedAt>=cutoff).OrderByDescending(x=>x.DeletedAt).Select(x=>new{x.Id,x.Name,x.Revision,x.DeletedAt}).ToListAsync(ct);return Results.Ok(items);});
    group.MapPost("/",async(CreateProjectRequest request,AppDbContext db,ClaimsPrincipal user,CancellationToken ct)=>{if(!ValidName(request.Name))return Results.Problem(statusCode:400,title:"Project name is required and limited to 120 characters");if(!ConfigValidator.TryValidate(request.ConfigJson,out var error))return InvalidConfig(error);var project=new Project{OwnerId=UserId(user)!,Name=request.Name.Trim(),ConfigJson=request.ConfigJson};var version=new ProjectVersion{Project=project,ConfigJson=request.ConfigJson,CreatedBy=project.OwnerId,Reason="created"};project.CurrentVersionId=version.Id;db.AddRange(project,version);await db.SaveChangesAsync(ct);return Results.Created($"/api/projects/{project.Id}",Dto(project));});
    group.MapGet("/{id:guid}",async(Guid id,AppDbContext db,ClaimsPrincipal user,CancellationToken ct)=>await Owned(db,user,id,false,ct) is { } p?Results.Ok(Dto(p)):Results.NotFound());
    group.MapPatch("/{id:guid}",async(Guid id,RenameProjectRequest request,AppDbContext db,ClaimsPrincipal user,CancellationToken ct)=>{if(!ValidName(request.Name))return Results.Problem(statusCode:400,title:"Project name is required and limited to 120 characters");var p=await Owned(db,user,id,false,ct);if(p is null)return Results.NotFound();if(p.Revision!=request.ExpectedRevision)return Conflict(p.Revision);p.Name=request.Name.Trim();p.Revision++;p.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync(ct);return Results.Ok(Dto(p));});
    group.MapPut("/{id:guid}/draft",async(Guid id,SaveDraftRequest request,AppDbContext db,ClaimsPrincipal user,CancellationToken ct)=>{if(!ConfigValidator.TryValidate(request.ConfigJson,out var error))return InvalidConfig(error);var p=await Owned(db,user,id,false,ct);if(p is null)return Results.NotFound();if(p.Revision!=request.ExpectedRevision)return Conflict(p.Revision);await using var tx=await db.Database.BeginTransactionAsync(ct);var v=new ProjectVersion{ProjectId=p.Id,ConfigJson=request.ConfigJson,CreatedBy=p.OwnerId,Reason=request.Reason??"autosave"};p.ConfigJson=request.ConfigJson;p.CurrentVersionId=v.Id;p.Revision++;p.UpdatedAt=DateTime.UtcNow;db.ProjectVersions.Add(v);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Results.Ok(Dto(p));});
    group.MapPost("/{id:guid}/duplicate",async(Guid id,AppDbContext db,ClaimsPrincipal user,CancellationToken ct)=>{var source=await Owned(db,user,id,false,ct);if(source is null)return Results.NotFound();var copy=new Project{OwnerId=source.OwnerId,Name=$"{source.Name} — Copy",ConfigJson=source.ConfigJson};var v=new ProjectVersion{Project=copy,ConfigJson=copy.ConfigJson,CreatedBy=copy.OwnerId,Reason="duplicated"};copy.CurrentVersionId=v.Id;db.AddRange(copy,v);await db.SaveChangesAsync(ct);return Results.Created($"/api/projects/{copy.Id}",Dto(copy));});
    group.MapDelete("/{id:guid}",async(Guid id,AppDbContext db,ClaimsPrincipal user,CancellationToken ct)=>{var p=await Owned(db,user,id,false,ct);if(p is null)return Results.NotFound();p.DeletedAt=DateTime.UtcNow;p.Revision++;await db.SaveChangesAsync(ct);return Results.NoContent();});
    group.MapPost("/{id:guid}/restore",async(Guid id,AppDbContext db,ClaimsPrincipal user,CancellationToken ct)=>{var p=await Owned(db,user,id,true,ct);if(p is null)return Results.NotFound();var retention=DateTime.UtcNow.AddDays(-30);if(p.DeletedAt is null||p.DeletedAt<retention)return Results.Problem(statusCode:410,title:"Restore window expired");p.DeletedAt=null;p.Revision++;p.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync(ct);return Results.Ok(Dto(p));});
  }
  public static void MapVersionEndpoints(this WebApplication app){var g=app.MapGroup("/api/projects/{projectId:guid}/versions").RequireAuthorization().RequireRateLimiting("standard");
    g.MapGet("/",async(Guid projectId,AppDbContext db,ClaimsPrincipal user,int page=1,int pageSize=20,CancellationToken ct=default)=>{if(await Owned(db,user,projectId,false,ct) is null)return Results.NotFound();page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,1,50);var q=db.ProjectVersions.AsNoTracking().Where(x=>x.ProjectId==projectId).OrderByDescending(x=>x.CreatedAt);var total=await q.CountAsync(ct);var items=await q.Skip((page-1)*pageSize).Take(pageSize).Select(x=>new{x.Id,x.SchemaVersion,x.CreatedAt,x.CreatedBy,x.Reason}).ToListAsync(ct);return Results.Ok(new{items,page,pageSize,total});});
    g.MapPost("/",async(Guid projectId,CreateVersionRequest request,AppDbContext db,ClaimsPrincipal user,CancellationToken ct)=>{var p=await Owned(db,user,projectId,false,ct);if(p is null)return Results.NotFound();var v=new ProjectVersion{ProjectId=p.Id,ConfigJson=p.ConfigJson,CreatedBy=p.OwnerId,Reason=request.Reason};db.Add(v);await db.SaveChangesAsync(ct);return Results.Created($"/api/projects/{p.Id}/versions/{v.Id}",new{v.Id,v.CreatedAt,v.Reason});});
    g.MapPost("/{versionId:guid}/restore",async(Guid projectId,Guid versionId,AppDbContext db,ClaimsPrincipal user,CancellationToken ct)=>{var p=await Owned(db,user,projectId,false,ct);if(p is null)return Results.NotFound();var old=await db.ProjectVersions.SingleOrDefaultAsync(x=>x.Id==versionId&&x.ProjectId==projectId,ct);if(old is null)return Results.NotFound();await using var tx=await db.Database.BeginTransactionAsync(ct);var restored=new ProjectVersion{ProjectId=p.Id,ConfigJson=old.ConfigJson,CreatedBy=p.OwnerId,Reason=$"restored:{old.Id}"};p.ConfigJson=old.ConfigJson;p.CurrentVersionId=restored.Id;p.Revision++;p.UpdatedAt=DateTime.UtcNow;db.Add(restored);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Results.Ok(Dto(p));});
  }
  public static void MapScenarioEndpoints(this WebApplication app){var g=app.MapGroup("/api/projects/{projectId:guid}/scenarios").RequireAuthorization().RequireRateLimiting("standard");
    g.MapGet("/",async(Guid projectId,AppDbContext db,ClaimsPrincipal user,int page=1,int pageSize=20,CancellationToken ct=default)=>{if(await Owned(db,user,projectId,false,ct) is null)return Results.NotFound();page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,1,50);var q=db.Scenarios.AsNoTracking().Where(x=>x.ProjectId==projectId).OrderByDescending(x=>x.CreatedAt);var total=await q.CountAsync(ct);var items=(await q.Skip((page-1)*pageSize).Take(pageSize).ToListAsync(ct)).Select(Dto).ToList();return Results.Ok(new PagedResponse<ScenarioDto>(items,page,pageSize,total));});
    g.MapPost("/",async(Guid projectId,ScenarioRequest r,AppDbContext db,ClaimsPrincipal user,CancellationToken ct)=>{if(!ValidName(r.Name))return Results.Problem(statusCode:400,title:"Scenario name is required and limited to 120 characters");if(r.SimulationConfigJson.Length>500_000||r.ResultSummaryJson.Length>100_000)return Results.Problem(statusCode:413,title:"Scenario payload too large");if(await Owned(db,user,projectId,false,ct) is null)return Results.NotFound();var baseExists=await db.ProjectVersions.AnyAsync(x=>x.Id==r.BaseVersionId&&x.ProjectId==projectId,ct);if(!baseExists)return Results.Problem(statusCode:422,title:"Invalid base version");var s=new Scenario{ProjectId=projectId,Name=r.Name.Trim(),BaseVersionId=r.BaseVersionId,SimulationConfigJson=r.SimulationConfigJson,ResultSummaryJson=r.ResultSummaryJson};db.Add(s);await db.SaveChangesAsync(ct);return Results.Created($"/api/projects/{projectId}/scenarios/{s.Id}",Dto(s));});
    g.MapPatch("/{id:guid}",async(Guid projectId,Guid id,RenameScenarioRequest r,AppDbContext db,ClaimsPrincipal user,CancellationToken ct)=>{if(!ValidName(r.Name))return Results.Problem(statusCode:400,title:"Scenario name is required and limited to 120 characters");if(await Owned(db,user,projectId,false,ct) is null)return Results.NotFound();var s=await db.Scenarios.SingleOrDefaultAsync(x=>x.Id==id&&x.ProjectId==projectId,ct);if(s is null)return Results.NotFound();s.Name=r.Name.Trim();await db.SaveChangesAsync(ct);return Results.Ok(Dto(s));});
    g.MapDelete("/{id:guid}",async(Guid projectId,Guid id,AppDbContext db,ClaimsPrincipal user,CancellationToken ct)=>{if(await Owned(db,user,projectId,false,ct) is null)return Results.NotFound();var s=await db.Scenarios.SingleOrDefaultAsync(x=>x.Id==id&&x.ProjectId==projectId,ct);if(s is null)return Results.NotFound();db.Remove(s);await db.SaveChangesAsync(ct);return Results.NoContent();});
  }
  public static void MapSharingEndpoints(this WebApplication app){var g=app.MapGroup("/api/projects/{projectId:guid}/shares").RequireAuthorization().RequireRateLimiting("sensitive");
    g.MapGet("/",async(Guid projectId,AppDbContext db,ClaimsPrincipal user,CancellationToken ct)=>await Owned(db,user,projectId,false,ct) is null?Results.NotFound():Results.Ok(await db.ShareLinks.Where(x=>x.ProjectId==projectId).Select(x=>new{x.Id,x.Permission,x.ExpiresAt,x.RevokedAt,x.CreatedAt}).ToListAsync(ct)));
    g.MapPost("/",async(Guid projectId,ShareRequest r,AppDbContext db,ClaimsPrincipal user,IConfiguration config,CancellationToken ct)=>{if(await Owned(db,user,projectId,false,ct) is null)return Results.NotFound();if(r.ExpiresAt<=DateTime.UtcNow)return Results.Problem(statusCode:422,title:"Expiry must be in the future");var raw=Convert.ToBase64String(RandomNumberGenerator.GetBytes(32)).Replace('+','-').Replace('/','_').TrimEnd('=');var hash=TokenHash(raw,config);var link=new ShareLink{ProjectId=projectId,TokenHash=hash,ExpiresAt=r.ExpiresAt};db.Add(link);await db.SaveChangesAsync(ct);return Results.Created($"/api/projects/{projectId}/shares/{link.Id}",new{link.Id,token=raw,url=$"/shared/{raw}",link.ExpiresAt});});
    g.MapDelete("/{id:guid}",async(Guid projectId,Guid id,AppDbContext db,ClaimsPrincipal user,CancellationToken ct)=>{if(await Owned(db,user,projectId,false,ct) is null)return Results.NotFound();var link=await db.ShareLinks.SingleOrDefaultAsync(x=>x.Id==id&&x.ProjectId==projectId,ct);if(link is null)return Results.NotFound();link.RevokedAt=DateTime.UtcNow;await db.SaveChangesAsync(ct);return Results.NoContent();});
    app.MapGet("/api/shared/{token}",async(string token,AppDbContext db,IConfiguration config,CancellationToken ct)=>{var hash=TokenHash(token,config);var link=await db.ShareLinks.AsNoTracking().Include(x=>x.Project).SingleOrDefaultAsync(x=>x.TokenHash==hash,ct);if(link is null||link.RevokedAt is not null||link.ExpiresAt<=DateTime.UtcNow)return Results.NotFound();return Results.Ok(new{project=new{link.Project.Id,link.Project.Name,link.Project.ConfigJson},permission="read",link.ExpiresAt});}).RequireRateLimiting("sensitive");
  }
  private static string TokenHash(string raw,IConfiguration config)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(raw+(config["ShareTokenPepper"]??throw new InvalidOperationException("ShareTokenPepper missing")))));
  public static void MapAccountDataEndpoints(this WebApplication app){var g=app.MapGroup("/api/account").RequireAuthorization().RequireRateLimiting("sensitive");
    g.MapGet("/export",async(AppDbContext db,ClaimsPrincipal user,CancellationToken ct)=>{var uid=UserId(user)!;var projects=await db.Projects.IgnoreQueryFilters().AsNoTracking().Where(x=>x.OwnerId==uid).Select(x=>new{x.Id,x.Name,x.ConfigJson,x.Revision,x.CreatedAt,x.UpdatedAt,x.DeletedAt,versions=x.Versions.Select(v=>new{v.Id,v.SchemaVersion,v.ConfigJson,v.CreatedAt,v.Reason}),scenarios=x.Scenarios.Select(s=>new{s.Id,s.Name,s.BaseVersionId,s.SimulationConfigJson,s.ResultSummaryJson,s.CreatedAt}),shares=x.ShareLinks.Select(s=>new{s.Id,s.Permission,s.ExpiresAt,s.RevokedAt,s.CreatedAt})}).ToListAsync(ct);return Results.Ok(new{schemaVersion=1,exportedAt=DateTime.UtcNow,user=new{id=uid,email=user.FindFirstValue(ClaimTypes.Email)},projects});});
    g.MapDelete("/",async(AppDbContext db,ClaimsPrincipal principal,UserManager<ApplicationUser> users,SignInManager<ApplicationUser> signIn,IWebHostEnvironment env,CancellationToken ct)=>{var uid=UserId(principal)!;var projectIds=await db.Projects.IgnoreQueryFilters().Where(x=>x.OwnerId==uid).Select(x=>x.Id).ToListAsync(ct);var reportIds=await db.Reports.IgnoreQueryFilters().Where(x=>projectIds.Contains(x.ProjectId)).Select(x=>x.Id).ToListAsync(ct);var projects=await db.Projects.IgnoreQueryFilters().Where(x=>projectIds.Contains(x.Id)).ToListAsync(ct);db.Projects.RemoveRange(projects);await db.SaveChangesAsync(ct);var reportDir=Path.Combine(env.WebRootPath??Path.Combine(env.ContentRootPath,"wwwroot"),"reports");foreach(var reportId in reportIds){var path=Path.Combine(reportDir,$"{reportId:N}.pdf");if(File.Exists(path))File.Delete(path);}var account=await users.FindByIdAsync(uid);if(account is null)return Results.NotFound();var result=await users.DeleteAsync(account);if(!result.Succeeded)return Results.Problem(statusCode:500,title:"Account deletion failed");await signIn.SignOutAsync();return Results.NoContent();});
  }
  public static void MapReportEndpoints(this WebApplication app){var g=app.MapGroup("/api/projects/{projectId:guid}/reports").RequireAuthorization().RequireRateLimiting("sensitive");
    g.MapGet("/",async(Guid projectId,AppDbContext db,ClaimsPrincipal user,CancellationToken ct)=>await Owned(db,user,projectId,false,ct) is null?Results.NotFound():Results.Ok((await db.Reports.AsNoTracking().Where(x=>x.ProjectId==projectId).OrderByDescending(x=>x.CreatedAt).ToListAsync(ct)).Select(Dto)));
    g.MapPost("/",async(Guid projectId,ReportRequest r,AppDbContext db,ClaimsPrincipal user,ReportQueue queue,CancellationToken ct)=>{if(await Owned(db,user,projectId,false,ct) is null)return Results.NotFound();if(r.ScenarioId is not null&&!await db.Scenarios.AnyAsync(x=>x.Id==r.ScenarioId&&x.ProjectId==projectId,ct))return Results.Problem(statusCode:422,title:"Invalid scenario");var report=new Report{ProjectId=projectId,ScenarioId=r.ScenarioId};db.Add(report);await db.SaveChangesAsync(ct);if(!queue.Enqueue(report.Id)){report.Status="failed";report.Error="Report queue is full. Retry later.";await db.SaveChangesAsync(ct);return Results.Problem(statusCode:503,title:"Report queue unavailable");}return Results.Accepted($"/api/projects/{projectId}/reports/{report.Id}",Dto(report));});
    g.MapGet("/{id:guid}/file",async(Guid projectId,Guid id,AppDbContext db,ClaimsPrincipal user,IWebHostEnvironment env,CancellationToken ct)=>{if(await Owned(db,user,projectId,false,ct) is null)return Results.NotFound();var report=await db.Reports.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id&&x.ProjectId==projectId&&x.Status=="succeeded",ct);if(report is null)return Results.NotFound();var path=Path.Combine(env.WebRootPath??Path.Combine(env.ContentRootPath,"wwwroot"),"reports",$"{id:N}.pdf");return File.Exists(path)?Results.File(path,"application/pdf",$"ac-thermal-{id:N}.pdf",enableRangeProcessing:true):Results.NotFound();});
  }
}
